version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/html/
file_exists_behavior: OVERWRITE
permissions:
    - object: /home/ubuntu/html/
      owner: www-data
      group: www-data
hooks:
  BeforeInstall:
    - location: scripts/cleanup
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: scripts/install_dependencies
  #     timeout: 300
  #     runas: ubuntu
  #   - location: scripts/configure_project
  #     timeout: 300
  #     runas: ubuntu