<?php

return array (
  'version' => '5.5.1',
  'title' => 'Papeletas',
  'type' => 'posicion',
  'id' => '6171b48824cd5',
  'updated' => 1634918525,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '6172e066245a1c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Periodo Electoral Relacionado',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_616f51f6c443c',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172e066245a1c',
    ),
    '6172d8f96dd2f0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Partido Relacionado',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61702ca47a8e1',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'name' => '6172d8f96dd2f0',
    ),
    '6172d79da5a1cc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Gobernador',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_616f4e794b61a',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172d79da5a1cc',
    ),
    '6172df81eb8520' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Consejo Legislativo Lista',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_616f4f044b61c',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172df81eb8520',
    ),
    '6172df8a7ba5e4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Consejo Legislativo Nominal',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_616f4f2a4b61d',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172df8a7ba5e4',
    ),
    '6172d7a3f6c8b4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Alcalde',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_616f4ee94b61b',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172d7a3f6c8b4',
    ),
    '6172dfa8b26e98' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Consejo Municipal Nominal',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_617223532546e',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172dfa8b26e98',
    ),
    '6172df9d589374' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Consejo Municipal Lista',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6172234f2546d',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172df9d589374',
    ),
    '6171b471589374' => 
    array (
      'type' => 'column-acf_field',
      'label' => '<span class="dashicons dashicons-screenoptions"></span> Columna',
      'width' => '100',
      'width_unit' => 'px',
      'field' => 'field_61702f7e338cb',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6171b471589374',
    ),
    '6171b45c181064' => 
    array (
      'type' => 'column-acf_field',
      'label' => '<span class="dashicons dashicons-screenoptions"></span> Fila',
      'width' => '100',
      'width_unit' => 'px',
      'field' => 'field_61702fe3338cc',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6171b45c181064',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);