<?php

return array (
  'version' => '5.5.1',
  'title' => 'Partidos',
  'type' => 'partido',
  'id' => '6172d86edbc94',
  'updated' => 1634916512,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '6172d82c947ae0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Logo',
      'width' => '60',
      'width_unit' => 'px',
      'field' => 'field_616f50e4ea80b',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172d82c947ae0',
    ),
    '6172d83a55c290' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Poster Horizontal',
      'width' => '60',
      'width_unit' => 'px',
      'field' => 'field_616f5012ea80a',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172d83a55c290',
    ),
    '6172d8499fbe78' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Color',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_616f4ffbea809',
      'export' => 'off',
      'sort' => 'off',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'off',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6172d8499fbe78',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);