#!/bin/bash
echo "Installing Dependencies"
# https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-simple-codecommit.html
# LEP Stack
#sudo apt-get install -y nginx php7.4 php7.4-fpm php7.4-cli php7.4-mysql php7.4-curl php7.4-json php-simplexml
#sudo systemctl start nginx
#sudo systemctl enable nginx
#sudo systemctl start php7.4-fpm
#sudo systemctl enable php7.4-fpm
# TODO: Create Nginx Site https://www.rosehosting.com/blog/how-to-install-php-7-4-with-nginx-on-ubuntu-20-04/
# TODO: Create .env variable
# Install Project Dependencies
#sudo apt install -y composer
# Fix Permissions
# sudo chown www-data:www-data -R *
# sudo chmod 755 -R *

## Install Composer v2
cd
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv /home/ubuntu/composer.phar /usr/bin/composer